config/routes.rb
MeetMagic::Application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get '/get_started', to: 'home#get_started'
  get '/user', to: 'user#show'
  get '/map', to: 'map#show'
  get '/list_view', to: 'search#list_view'
  get '/get_all_user_coords', to: 'map#get_all_user_coords'
  get '/get_current_user_coords', to: 'map#get_current_user_coords'
  get '/users_near_me', to: 'user#users_near_me'
  get '/all_users', to: 'user#all_users'
  get '/find_user', to: 'user#find_user'
  get '/search', to: 'search#search'
end

app/models/info.rb
class Info <ActiveRecord::Base
	belongs_to :user
	serialize :lat_lng, Hash

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :infos
	serialize :lat_lng, Hash
	# serialize :info, Hash
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  geocoded_by :location
  after_validation :geocode
  after_save :populate_info

  def populate_info
    info = Info.new("name" => self.name, "email" => self.email, "location" => self.location, "level" => self.level, "score" => self.score, "mentor" => self.mentor, "lat_lng" => {lat: self.latitude, lng: self.longitude})
  	self.infos << info
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :level, :mentor, :score, :location, :email, :password, :password_confirmation)
    end
  end


 #  class Rack::Request
	# 	def ip
	# 		'184.154.83.119'
	# 	end
	# end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	respond_to :json

	def index

		if current_user
			location = [current_user.latitude, current_user.longitude]
		else
			location = [request.location.latitude, request.location.longitude]
		end

		@nearby_users_count = User.near(location).count
		@all_users_count = User.all.count
	end

	def get_started
	end
end

app/controllers/map_controller.rb
class MapController < ApplicationController

	def show
		unless current_user
			redirect_to new_user_session_path
		end
	end

	def get_current_user_coords
		if current_user
			lat, lng = current_user.latitude, current_user.longitude
		else
			lat, lng = request.location.latitude, request.location.longitude
		end
			render json: {coords: {lat: lat, lng: lng}}
	end

	def get_all_user_coords
		points = Info.where('level = ? or mentor = true', current_user.level)
		render json: {points: points}
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	respond_to :json

	def search
		if request.xhr?
			@input = capitalize_helper(params[:query])
		else
			@input = capitalize_helper(params[:search][:input])
		end

		@users = User.find(:all, conditions: ['location LIKE ? OR name LIKE ?', "%#{@input}%", "%#{@input}%"])
		@users.sort_by!{|u| -u.level}

		render layout: false
	end

	def list_view
		location = [current_user.latitude, current_user.longitude]
		@nearby_users_count = User.near(location).count
		@all_users_count = User.all.count
	end	

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	respond_to :json


	def users_near_me
		if current_user
			@nearby_users = current_user.nearbys(10).sort_by{|u| -u.level}
		else
			@nearby_users = User.near([request.location.latitude, request.location.longitude]).sort_by{|u| -u.level}
		end

		render layout: false
	end

	def all_users
		@users = User.all
		@users.sort_by!{|u| u.location}

		render layout: false
	end

	def show
		unless current_user
		 redirect_to new_user_session_path
		end
		@user = User.find(params[:format])
	end

	def find_user
		binding.pry
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def capitalize_helper query
		query.split.map! do |word|
			word.capitalize
		end
		.join(" ")
	end
end

app/views/home/get_started.html.erb
<div class="getting-started">
	<h1>Getting Started with MeeTG</h1>

	<ul class="getting-started-steps">
		<li class="step-headers">Sign Up or Log in
				<ul class="sub-steps">
					<li>Select how many years you have been playing, this will match you with up with equally skilled players</li>
					<li>Select if you would like to mentor players at a lower level than you</li>
				</ul>
		</li>
		<li class="step-headers">Click "Map" to browse players located in your area
			<ul class="sub-steps">
				<li>You can click on markers to expand nearby players OR open up their quick-info boxes</li>
				<li>Clicking "Contact" will open up your default email to connect with the player!</li>
			</ul>
		</li>
		<li class="step-headers">Search for Locations or Users in the search bar
			<ul class="sub-steps">
				<li>This will bring up a list of search results</li>
				<li>Click on the player names to view their contact page</li>
			</ul>
		</li>
	</ul>
</div>

app/views/home/index.html.erb
<br>
<div class="landing-info">
	<h1>Find M:TG Players</h1>
	<h1>Near You!</h1>
	<%= link_to "Get Started!", get_started_path, class: 'get-started'  %>
	<h3> <%= @nearby_users_count  %> Players near you!</h3>
</div>

app/views/home/map.html.erb
<div id="map-canvas" class="map"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMVzs0GyFguJHfTNtxDyZFtG3RQbRICGU&sensor=true"></script>
<body onload="initializeMap()">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeetMagic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
</head>
<body>

		<div class="nav">
			<ul class="nav-bar">
				<% if  current_user %> 	

					<li> Hello, <%= current_user.name  %></li>
					<li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
					<li><%= link_to "Edit Info", edit_user_registration_path  %></li>
					<li><%= link_to "Map View", map_path  %></li>
					<li><%= link_to "List View", list_view_path  %></li>
				<% else %>
			  	<li><%= link_to "Sign Up", new_user_registration_path, id: "sign-up"%></li>
			  	<li><%= link_to "Log In", new_user_session_path, id: "log-in"  %></li>				
				<% end %>
				<li class="title"><%= link_to "Meet Magic", root_path%></li>
		  </ul>
		</div>
		<br>
		
	<div class="wrapper">
	
		<p class="alert"><%= alert %></p>
		<p class="notice"><%= notice %></p>

		<%= yield %>
	</div>

</body>
</html>

app/views/map/show.html.erb
<br>
<%= form_for :map_search, html: {id: 'map-search', class: 'map-search'} do |f|  %>
	<%= f.text_field :input, placeholder: 'Search a location'  %>
	<%= f.submit %>
<% end %>
<div id="map-canvas" class="map"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMVzs0GyFguJHfTNtxDyZFtG3RQbRICGU&sensor=true"></script>
<%= javascript_include_tag "overlappingMarkerSpiderfier.js"  %>
<body onload="initializeMap()">

app/views/search/list_view.html.erb
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=true"></script>

<div class="list-view">

	<%= form_for :search, url: '/search', method: 'get', html: {class: 'search-box', id: 'search'} do |f| %>
		<%=	f.text_field :input, id: 'search-input', placeholder: "Search a location/user" %>
		<%= f.submit("Search") %>
	<% end %>

	<h3> <%= link_to "#{@nearby_users_count} players near you!",  users_near_me_path, class: 'list-view-link' %>  <%= link_to "#{@all_users_count} players total", all_users_path, class: 'list-view-link' %></h3>
	<div class="append-users-here"></div>
</div>

<body onload="initializeAutoComplete()">

app/views/search/search.html.erb
<%= render partial: 'user/list_users', locals: {users: @users, title: "Search Results for #{@input}"}  %>

app/views/user/_list_users.html.erb
<div class="list-users">
	<h2><%= title  %></h2>

<% if users.length ==  0%>
	<h3>OOPS! There doesn't seem to be anybody here</h3>	
<% end %>

	<ul>
		<% users.each do |user| %>
			<li> <%= link_to user.name, user_path(user.id) %> - Level <%= user.level %> <span class="mentor"><%=" - mentor" if user.mentor %></span> - <%= user.location  %></li>
		<% end %>
	</ul>
</div>

app/views/user/all_users.html.erb
<%= render partial: 'list_users', locals: {users: @users, title: "All Users"}  %>

app/views/user/show.html.erb
<div class="user-page">
	<h2><%= @user.name %>'s Contact Page</h2>
	<ul>
		<li><span class="user-profile-category">Location:</span> <span class="user-profile-data"><%= @user.location  %></span></li>
		<li><span class="user-profile-category">Level:</span> <span class="user-profile-data"><%= @user.level  %></span></li>		
		<li>Is <% unless @user.mentor %> not <% end %> a mentor</li>
		<li><span class="user-profile-category">Email:</span> <span class="user-profile-data"><%= mail_to @user.email %></span></li>
	</ul>
</div>

app/views/user/users_near_me.html.erb
<%= render partial: "list_users", locals: {users: @nearby_users, title: "Users Near Me"} %>